# Generated by Django 4.2.16 on 2024-12-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("coursename", models.CharField(max_length=16, verbose_name="课程名")),
                ("starttime", models.TimeField(verbose_name="课程开始时间")),
                ("endtime", models.TimeField(verbose_name="课程结束时间")),
                ("weekday", models.IntegerField(verbose_name="课程设置日期")),
            ],
        ),
        migrations.CreateModel(
            name="StuInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stuname", models.CharField(max_length=32, verbose_name="学生姓名")),
                ("stuid", models.CharField(max_length=16, verbose_name="学生学号")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("UserId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=16, verbose_name="用户名")),
                ("password", models.CharField(max_length=16, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="UserStudentLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.stuinfo",
                        verbose_name="学生id",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.userinfo",
                        verbose_name="用户id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSelect",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.courseinfo",
                        verbose_name="课程",
                    ),
                ),
                (
                    "stuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.stuinfo",
                        verbose_name="选课学生",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("starttime", models.TimeField(verbose_name="考勤开始时间")),
                ("endtime", models.TimeField(verbose_name="考勤结束时间")),
                (
                    "courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.courseinfo",
                        verbose_name="课程",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendenceLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attendtime", models.TimeField(verbose_name="考勤时间")),
                (
                    "requestid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.attendrequest",
                        verbose_name="课程",
                    ),
                ),
                (
                    "stuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.stuinfo",
                        verbose_name="学生",
                    ),
                ),
            ],
        ),
    ]
