# Generated by Django 4.2.16 on 2024-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendencelog",
            name="attendtime",
            field=models.DateTimeField(verbose_name="考勤时间"),
        ),
    ]
