# Generated by Django 4.2.16 on 2024-12-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_attendencelog_attendtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendrequest",
            name="endtime",
            field=models.DateTimeField(verbose_name="考勤结束时间"),
        ),
        migrations.AlterField(
            model_name="attendrequest",
            name="starttime",
            field=models.DateTimeField(verbose_name="考勤开始时间"),
        ),
    ]
