# Generated by Django 4.2.16 on 2024-12-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_attendrequest_endtime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicBuilding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("buildingname", models.CharField(max_length=16, verbose_name="教学楼名称")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
            ],
        ),
        migrations.AddField(
            model_name="courseinfo",
            name="buildingid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.academicbuilding",
                verbose_name="教学楼",
            ),
            preserve_default=False,
        ),
    ]
