# Generated by Django 4.2.16 on 2024-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_academicbuilding_courseinfo_buildingid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicbuilding",
            name="buildingname",
            field=models.CharField(max_length=16, unique=True, verbose_name="教学楼名称"),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="stuname",
            field=models.CharField(max_length=32, unique=True, verbose_name="学生姓名"),
        ),
    ]
