# Generated by Django 4.2.16 on 2024-12-03 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_academicbuilding_buildingname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseinfo",
            name="buildingid",
        ),
        migrations.DeleteModel(
            name="AcademicBuilding",
        ),
    ]
