# Generated by Django 4.2.16 on 2024-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_courseinfo_buildingid_delete_academicbuilding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuinfo",
            name="stuid",
            field=models.CharField(max_length=16, unique=True, verbose_name="学生学号"),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="stuname",
            field=models.CharField(max_length=32, verbose_name="学生姓名"),
        ),
    ]
