# Generated by Django 4.2.16 on 2024-12-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_stuinfo_stuid_alter_stuinfo_stuname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=16, unique=True, verbose_name="用户名"),
        ),
    ]
